// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.18.0

package compositions

import ()

type Composition struct {
	ID         int64
	ComposerID int64
	Name       string
	Version    int64
}
