// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.18.0

package composers

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Composer struct {
	ID          int64
	FirstName   string
	LastName    string
	ImageLink   pgtype.Text
	Description pgtype.Text
	Version     int64
}
