// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.18.0

package mirrors

import ()

type CompositionMirror struct {
	ID            int64
	CompositionID int64
	Link          string
	Version       int64
}
